set(CMAKE_CROSSCOMPILING ON)

set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_PROCESSOR "z80")
set(CMAKE_EXECUTALE_FORMAT "ELF")

# Force C compiler OK
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_ASM_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_ASM_COMPILER	"sdcc")
set(CMAKE_C_COMPILER 	"sdcc")
set(CMAKE_LINKER        "sdcc")

set(FLAGS "-mz80 --nostdlib --nostdinc --no-std-crt0")
set(CMAKE_C_OUTPUT_EXTENSION ".rel")
set(CMAKE_CXX_OUTPUT_EXTENSION ".rel")

set(CMAKE_ASM_FLAGS 		    "${CMAKE_ASM_FLAGS} ${FLAGS}" CACHE STRING "ASM Flags")
set(CMAKE_C_FLAGS		        "${CMAKE_C_FLAGS} ${FLAGS}" CACHE STRING "C Flags")
set(CMAKE_EXE_LINKER_FLAGS 		"${CMAKE_EXE_LINKER_FLAGS} ${FLAGS}" CACHE INTERNAL "EXE Linker Flags")
set(CMAKE_SHARED_LINKER_FLAGS 	"${CMAKE_SHARED_LINKER_FLAGS} ${FLAGS}" CACHE INTERNAL "Shared Linker Flags")
set(CMAKE_MODULE_LINKER_FLAGS 	"${CMAKE_MODULE_LINKER_FLAGS} ${FLAGS}" CACHE INTERNAL "Module Linker Flags")